### ISSUE TITLE
/tmp/web_api_key.txt error

### ISSUE THREAD

**Issue by godsgood33** [madeofpendletonwool/PinePods#114]
Just installed the latest version and I'm getting errors from `/pinepods/main.py`, line 60 as it can't find `/tmp/web_api_key.txt`.  I just touched the file and the error goes away, but I'm sure that misses something.

```
Traceback (most recent call last):
  File "/pinepods/main.py", line 60, in <module>
    with open("/tmp/web_api_key.txt", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/web_api_key.txt'
2023-10-05 16:47:25,422 INFO exited: main_app (exit status 1; not expected)
2023-10-05 16:47:26,428 INFO spawned: 'main_app' with pid 78
2023-10-05 16:47:27,429 INFO success: main_app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by godsgood33** [comment]
Also, once I got this fixed, the next error has to do with the database table creation.  I don't know what version of MariaDB you're using, but I am connecting this to a MySQL server that I have on another system so that I can more easily backup my databases.  It's version 8.0.32 and the error seems to have to do with the User table creation

```
wait-for-it.sh: waiting 60 seconds for 192.168.1.3:3306
wait-for-it.sh: 192.168.1.3:3306 is available after 0 seconds
Traceback (most recent call last):
  File "/pinepods/startup/setupdatabase.py", line 48, in <module>
    cursor.execute("""
  File "/usr/local/lib/python3.12/site-packages/mysql/connector/cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql/connector/connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mysql/connector/connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1170 (42000): BLOB/TEXT column 'Username' used in key specification without a key length
```

When I change the "TEXT" fields to VARCHARs and set a length, the create statements work just fine.  Something also is happening that I'm not able to login once I create the container.

**Comment by madeofpendletonwool** [comment]
Hi @godsgood33. There was an issue opened previously on this that sort of died out after a time. https://github.com/madeofpendletonwool/PinePods/issues/74

Nonetheless, my first thought is permissions. That web_api_key.txt file gets created on first boot in the setupdatabase.py file 

`web_api_key = create_api_key(cnx)

with open("/tmp/web_api_key.txt", "w") as f:
    f.write(web_api_key)
`
In addition I've had an issue with SElinux causing the folder to not be writable which could be causing your problem. I discuss that here https://github.com/madeofpendletonwool/PinePods/issues/74#issuecomment-1670070582.

The container is capable of setting up it's own external folders provided it has permission to do so you shouldn't need to create your own folders that you mount via the compose file.

The other possibility is that the setupdatabase.py script could be erroring prior to getting to line 162 which is where it writes that file. Given that your using an external database and found an issue with that I would say that's probably most likely. 

As for that second issue, the users table gets setup in setupdatabase.py here

cursor.execute("""
    CREATE TABLE IF NOT EXISTS Users (
        UserID INT AUTO_INCREMENT PRIMARY KEY,
        Fullname TEXT,
        Username TEXT UNIQUE,
        Email VARCHAR(255),
        Hashed_PW CHAR(60),
        Salt CHAR(60),
        IsAdmin TINYINT(1),
        Reset_Code TEXT,
        Reset_Expiry DATETIME,
        MFA_Secret VARCHAR(50),
        TimeZone VARCHAR(50) DEFAULT 'UTC',
        TimeFormat INT  DEFAULT 24,
        FirstLogin TINYINT(1) DEFAULT 0
    )
""")

In fact, that file creates the entire database structure so that's your starting point there. As of this point, I haven't tested with an external database though it's certainly on the list to make that work. I need to get through some of the other glaring issues before I can take that on though. I just to don't have the capacity to get to that nice to have quite yet. mariadb version in all the tests I've done has just been latest

    image: mariadb:latest

I'll leave this open for the time being so getting external dbs working can be on the list of todos.

**Comment by godsgood33** [comment]
Yeah, I'd agree.

An easy change that should fix the issue and allow MySQL as a database type.  If the DB_TYPE ENV var is used and then add the following

```python
texttype = "TEXT"
if db_type == "mysql":
    texttype = "VARCHAR(255)"
```

**Comment by madeofpendletonwool** [comment]
The underlying issue to this has been discovered and will be patched in the next version coming very soon. It was due to an old dependancy on mysql-connector when the new version is mysql-connector-python is the newest version. Good old package naming. I will close this issue for now.
