### ISSUE TITLE
From pod_layout to Episode_layout error, empty window.

### ISSUE THREAD

**Issue by hollisticated-horse** [madeofpendletonwool/PinePods#152]
Hello, awesome project, will keep an eye on it. 

I was playing around with your demo instance (as `bloup`). 

I tried adding the _Pretending to be People_ podcast. It did so after a second try. I must have reloaded the page or reopened the browser. When I click on the title in pod_layout to go to the episode_layout page, It does not load. 

Might be a duplicate of [#134 ](https://github.com/madeofpendletonwool/PinePods/issues/134)

I'm using **Firefox  126.0** on **Arch Linux** and am up-to-date for firefox at least.  
Similar error with Chromium.

In the console, there are two errors. I've linked the logs below. 

[pinepod_error.console-export-2024-5-17_20-30-22.txt](https://github.com/madeofpendletonwool/PinePods/files/15355651/pinepod_error.console-export-2024-5-17_20-30-22.txt)

Interestingly, I get no error when clicking on the `see more` link

**Comment by madeofpendletonwool** [comment]
Good find! And thanks much for the detailed report! So many podcast feeds choose to be slightly different in syntax. The challenge is covering them all. Looks like the app tried to find a value in something that was empty in the feed. I'll take a closer look at the feed and figure out what's causing it. Expect a fix in the next release!

**Comment by madeofpendletonwool** [comment]
Oh, and this is unrelated to that other issue. Rust doesn't like None types (which I quite enjoy about it) but it makes for a very common issue!

**Comment by madeofpendletonwool** [comment]
I gotta say @hollisticated-horse , this feed has honestly really helpful. I have fixed a decent few issues with the way I was parsing feeds with this. Fixed an issue with podcast episode ordering because this feed is backwards from the standard, I found the reason the None error was happening was because there was a few episodes that don't have a duration listed, I fixed that, and implemented a function so that if an episode has a none duration it will handle it gracefully going forward. Finally, this feed showed me there was an issue with timestamps because this feed uses a different than what most podcasts do for timestamps. So honestly, while this feed doesn't follow many standards, it has been really helpful for finding edgecases. 

Fix for this plus a few other bugs rolling out tomorrow morning! Thanks again for opening the issue! I'll close this out since I'm rolling a fix out tomorrow morning. Feel free to open a new issue if you notice something else. 

PS This looks like a pretty cool podcast. Always looking for new actual plays. I'll check it out 👍

**Comment by hollisticated-horse** [comment]
Cheers, @madeofpendletonwool, happy to help. The podcast in question is pretty good imo. It's Delta Green RPG, lovecraftian horror but a bit like Men In Black. 

I'm looking into the responsiveness of the CSS now. I'll open a new issue later.
