### ISSUE TITLE
"Delete Podcast" functionality UX is not great

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#257]
This is on the 0.6.5 beta you made for me, `boc-test-this` (in case it's version specific).

When I delete a podcast, the UX is just not great. I press the "yes, delete podcast" button and then the message pops up to tell me it's deleted, but nothing else happens. So I need to take _some_ action to get past this point. It isn't immediately clear to me how I should proceed, from the state of things in this screenshot:

![image](https://github.com/user-attachments/assets/ee4e320b-e490-4ce9-a852-9e7f01f656bf)

When I hit the "X" on the delete prompt, I end up with this state, which is also a bit odd..

![image](https://github.com/user-attachments/assets/267b659e-d511-4ea7-af1a-6fddb7c27a89)

When I refresh the page, I get to this state which is a bit odd, maybe.. I think this is driven from the new URL params.

![image](https://github.com/user-attachments/assets/9adb160f-4a27-46eb-8caa-3ccbb1ccb68e)

I haven't given this extensive thought, but I wonder if the best option after the successful delete is to redirect back to the `/podcasts` page. :thinking:

**Comment by madeofpendletonwool** [comment]
Good point, it certainly should auto close the delete window after deleting a podcast. I hadn't noticed it didn't. I'm not sure that bumping you back to the /podcast page is the right call though. Because by design in Pinepods you can interact with a podcast in just about anyway without actually having it added. You can listen to episodes from a non-added podcast just like you would with an added podcast. Only thing you really can't do with an unadded podcast is take actions on the episodes, say like save the episodes, or download them. 

It's good that after refreshing you end up back on on the podcast page, as previously that would have caused a panic. You could resubscribe to the podcast from right there now if you wanted.

**Comment by madeofpendletonwool** [comment]
Alright, 0.6.5 just released and I fixed up a few things with this. The episode_layout page now handles removals and additions of podcasts much more gracefully, and in addition, when you click the delete button it now closes the modal and confirming. I think it's a much better experience now! Let me know what you think and I can reopen it if it would make sense to adjust the experience in another way. The docker images are currently building so just give it a bit before pulling!

https://github.com/madeofpendletonwool/PinePods/releases/tag/0.6.5
