### ISSUE TITLE
Issue playing feeds from simplecast.com

### ISSUE THREAD

**Issue by jonnyabu1** [madeofpendletonwool/PinePods#302]
I have three feeds that pull from feeds.simplecast.com.  Everything seems to work except playing the episodes.  The latest episodes show up and things like the description are fine.  I can download episodes and see them in the downloads folder.  If I manually play the mp3 that it downloaded it plays in something like VLC.  Even downloaded though they just won't play in the browser.  ( I wonder if it's actually still going out to the web and trying to stream it despite it being downloaded? )

An example:
https://feeds.simplecast.com/RV1USAfC

**Comment by jonnyabu1** [comment]
Oh, the feeds are synced with Nextcloud gpodder so that I can sync between Pinepods and AntennaPod.  The podcasts play fine in AntennaPod so I have to listen to them on the phone, but of course I would like to listen to them on my desktop when I'm sitting there at work

**Comment by madeofpendletonwool** [comment]
Hi @jonnyabu1, thanks for opening the issue! I'll take a look in the next couple days here. Apologies for not getting back sooner. I've had to focus on some different things. Check back soon!

**Comment by madeofpendletonwool** [comment]
Hi @jonnyabu1, I figured out why you are having this problem. I'm going to go out on a limb and say you likely have an ad-blocker installed on your browser. That, or you're using brave. Something about this particular feed is being caught by ad-blockers. That's also why downloading and playing works. Because it pulls the audio instead of streaming from the url that ad-blockers don't like. 
![image](https://github.com/user-attachments/assets/0a4aeeb1-f86a-4346-832c-5618c7b0df15)


This has happened one other time to a user in the discord. See the screenshot below for more info

![image](https://github.com/user-attachments/assets/f5500e1d-145e-4ef1-91fd-3dcdd46e2ea9)


Unfortunately, there's nothing I can really do. No matter what I were to do with Pinepods if  the ad-blocker in your browser doesn't like it, it will be blocked. You'll have to disable your adblocker for the Pinepods site, the url that the podcast redirects to, or use the client version of Pinepods.

**Comment by jonnyabu1** [comment]
Ah sorry about that.  You are correct.  At work I usually use Vivaldi, with UBlock Origin, and mostly Brave at home.  Testing around yep, it doesn't work in Brave with it's "Shields Up" ( ad blocker ) on but does with it off.  And in Firefox it doesn't work with UBlock Origin on but does with it off.  So yep, that is the cause.  Sorry to not even had that as a thought to look at
