### ISSUE TITLE
gpodder API support?

### ISSUE THREAD

**Issue by clach04** [madeofpendletonwool/PinePods#73]
Any plans for exist API support, e.g like gpodder so existing clients like https://github.com/AntennaPod/AntennaPod can be used?

**Comment by madeofpendletonwool** [comment]
Hey! Can you explain your request a bit more? I'm somewhat unclear on what your asking. Would you like to use antenna pod as a front end to interact with Pinepods? Or is the idea to access the feed for your podcasts in Pinepods using Antennapod?

The scope of the project is to be a management and listening solution for podcasts. All the Apis for the Pinepods backend are available and documented so if someone wanted to create a different client of some sort that would be doable. So in order to use a client like Antenna pod it would need to be able to interact with the Pinepods APIs.

**Comment by clach04** [comment]
I was thinking of the later. For multiple devices it would be nice to have feed and progress syncronized (e.g for off offline play). I've not got around to setting up a gpodder server yet and was wondering if I should check out PinePods. I saw someone asking you about antennapod on your Reddit announcement so thought I'd open an issue to find out more.

What benefits are there with your new API? It sounds like you need brand new clients to be built if offline players want to interact with PinePods?

**Comment by Simon-the-Sorcerer** [comment]
It would be nice to have multiple option for sync of podcasts. 

I use [nextcloud-gpodder](https://github.com/thrillfall/nextcloud-gpodder) to manage my listened podcasts with Antennapod. 
An interface to nextcloud-gpodder would be good so that the listened episodes are also marked as listened in Pinepod.

**Comment by madeofpendletonwool** [comment]
Ahh, I understand. Then actually that functionality you asked about is already added. Feed and progress is already synchronized. In fact everything is. That's really what the apis and user logins are for. Absolutely everything you do in PinePods is saved in the database and that interaction occurs over the apis. The intention there is so that when you do move to another device your experience is exactly the same. Your listen time, added episodes, server downloads, queue, even your theme. They're all stored on the database so moving to another device is seemless and it's easy to listen to half a podcast in one location and half in another.

As for the API benefits. The apis are really just providing the functionality needed to make the application function. Like play an episode, there's an api for that. Add a new user, change theme, download episode, all apis to make your listening experience seemless between devices. That's why I built PinePods to be honest. I was fed up with bad experiences between podcast apps not syncing my progress and such.

As for @Simon-the-Sorcerer suggestion. That's a really great idea and very doable. I could absolutely build in support for syncing of podcasts if you already use nextcloud gpodder. I'll dig into that.

We'll keep this issue open as I navigate nextcloud gpodder support and I'll get working on that.

**Comment by thejevans** [comment]
gpodder is a great place to start. I would love to test out your apps with my current gpodder backend to see if I like them without needing rebuild my set of subscriptions and listen history. Another thing that you might want to look at is the [open podcast api](https://openpodcastapi.org/index.html) which is being developed as a joint project between many of the players in the open-source podcasting space to extend and replace gpodder, as the gpodder project has been in maintenance-only mode for some time now.

**Comment by clach04** [comment]
Cool! I'd not heard or https://github.com/OpenPodcastAPI/api-specs before.

**Comment by lead0r** [comment]
I am using AntennaPod with nextcloud-gpodder as well, that works flawlessly with multiple Android devices, but I always wanted to have macOS application compatible with that setup as well. As I understand it, pinepods could potentially replace that altogether, right? I could listen to my feeds from different platforms and sync progress with the server?

**Comment by madeofpendletonwool** [comment]
Hey all, without the release of version 0.5 the nextcloud gpodder sync has been completed and added in! Pinepods will now sync podcasts in from nextcloud once connected so it's very easy to switch back and forth between this and antennapod. You can find this option in the settings. The entire app has been rebuilt on Rust so it's way faster and much more consistent. Now's the perfect time to give it another shot!
