### ISSUE TITLE
Add podcast from URL feed not working

### ISSUE THREAD

**Issue by lead0r** [madeofpendletonwool/PinePods#95]
When clicking the "Add podcast from URL feed", nothing happens. I tried multiple browsers and see nothing related in the logs.
I also want to add something from a UX perspective: It took me quite a while to find the button, because on the Home tab, it's possible to search for new podcasts but without the option to use a feed URL

**Comment by madeofpendletonwool** [comment]
Just an FYI, I will get to this among the other issues, however due to the beta nature of Pinepods currently I'm building up a lot of other aspects so it's difficult to switch to a smaller issue and then go back. Currently I'm adding the ability to tie specific features to apis for the authentication system and before that is released for the next release I'll have a look at this issue and fix anything that might be needed.

**Comment by madeofpendletonwool** [comment]
Hey @lead0r, this has been fixed in the next release. It'll be out in just a couple days. It worked previously on the client version but the web version had a bug preventing it from working which has been fixed. As for your second request, I'd prefer not to add the button to the home at this time. The button takes up screen real estate in the form of a row and I think adding it to the home screen would be better if left to just podcasts unfortunately. If there's additional requests to add that button to home I'll add it on but for now I think I'll leave it to just the podcasts page.
